
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUsers
{

    public AspNetUsers()
    {

        this.AspNetUserClaims = new HashSet<AspNetUserClaims>();

        this.AspNetUserLogins = new HashSet<AspNetUserLogins>();

        this.PEDIDOS_CLIENTES = new HashSet<PEDIDOS_CLIENTES>();

        this.PEDIDOS_PROVEEDORES = new HashSet<PEDIDOS_PROVEEDORES>();

        this.AspNetRoles = new HashSet<AspNetRoles>();

    }


    public string Id { get; set; }

    public string Email { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public string UserName { get; set; }



    public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual ICollection<PEDIDOS_CLIENTES> PEDIDOS_CLIENTES { get; set; }

    public virtual ICollection<PEDIDOS_PROVEEDORES> PEDIDOS_PROVEEDORES { get; set; }

    public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }

}

}
