
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CLIENTES
{

    public CLIENTES()
    {

        this.CUENTAS_CLIENTES = new HashSet<CUENTAS_CLIENTES>();

        this.PEDIDOS_CLIENTES = new HashSet<PEDIDOS_CLIENTES>();

        this.TIPO_FACTURACIONES = new HashSet<TIPO_FACTURACIONES>();

    }


    public int ClienteID { get; set; }

    public string Nombre { get; set; }

    public string RazonSocial { get; set; }

    public string CUIT_CUIL { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public int ProvinciaID { get; set; }

    public string Localidad { get; set; }

    public int CodPostal { get; set; }

    public string Latitud { get; set; }

    public string Longitud { get; set; }

    public Nullable<int> Zoom { get; set; }

    public string Telefono1 { get; set; }

    public string Telefono2 { get; set; }

    public string Mail1 { get; set; }

    public string Mail2 { get; set; }

    public decimal Descuento { get; set; }

    public string Comentarios { get; set; }

    public string UsuarioMercadolibre { get; set; }



    public virtual PROVINCIAS PROVINCIAS { get; set; }

    public virtual ICollection<CUENTAS_CLIENTES> CUENTAS_CLIENTES { get; set; }

    public virtual ICollection<PEDIDOS_CLIENTES> PEDIDOS_CLIENTES { get; set; }

    public virtual ICollection<TIPO_FACTURACIONES> TIPO_FACTURACIONES { get; set; }

}

}
