
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CUENTAS_CLIENTES
{

    public CUENTAS_CLIENTES()
    {

        this.MOVIMIENTOS_CLIENTES = new HashSet<MOVIMIENTOS_CLIENTES>();

    }


    public int CCuentaID { get; set; }

    public int ClienteID { get; set; }

    public string NumeroCuenta { get; set; }

    public string Descripcion { get; set; }



    public virtual CLIENTES CLIENTES { get; set; }

    public virtual ICollection<MOVIMIENTOS_CLIENTES> MOVIMIENTOS_CLIENTES { get; set; }

}

}
