
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CUENTAS_PROVEEDORES
{

    public CUENTAS_PROVEEDORES()
    {

        this.MOVIMIENTOS_PROVEEDORES = new HashSet<MOVIMIENTOS_PROVEEDORES>();

    }


    public int PCuentaID { get; set; }

    public int ProveedorID { get; set; }

    public string NumeroCuenta { get; set; }

    public string Descripcion { get; set; }



    public virtual PROVEEDORES PROVEEDORES { get; set; }

    public virtual ICollection<MOVIMIENTOS_PROVEEDORES> MOVIMIENTOS_PROVEEDORES { get; set; }

}

}
