
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MOVIMIENTOS_CLIENTES
{

    public int CMovimientoID { get; set; }

    public int CCuentaID { get; set; }

    public Nullable<int> PedidoClienteID { get; set; }

    public System.DateTime Fecha { get; set; }

    public decimal Debito { get; set; }

    public decimal Credito { get; set; }

    public string Detalle { get; set; }



    public virtual CUENTAS_CLIENTES CUENTAS_CLIENTES { get; set; }

}

}
