
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PEDIDOS_PROVEEDORES
{

    public PEDIDOS_PROVEEDORES()
    {

        this.PEDIDOS_PROVEEDORES_DETALLES = new HashSet<PEDIDOS_PROVEEDORES_DETALLES>();

        this.TIPO_PAGOS = new HashSet<TIPO_PAGOS>();

    }


    public int PedidoProveedorID { get; set; }

    public int EPedidoID { get; set; }

    public int ProveedorID { get; set; }

    public string AsignatarioID { get; set; }

    public decimal Total { get; set; }

    public Nullable<int> TFacturacionID { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

    public virtual ESTADOS_PEDIDOS ESTADOS_PEDIDOS { get; set; }

    public virtual TIPO_FACTURACIONES TIPO_FACTURACIONES { get; set; }

    public virtual ICollection<PEDIDOS_PROVEEDORES_DETALLES> PEDIDOS_PROVEEDORES_DETALLES { get; set; }

    public virtual PROVEEDORES PROVEEDORES { get; set; }

    public virtual ICollection<TIPO_PAGOS> TIPO_PAGOS { get; set; }

}

}
