
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PRODUCTOS
{

    public PRODUCTOS()
    {

        this.PEDIDOS_CLIENTES_DETALLES = new HashSet<PEDIDOS_CLIENTES_DETALLES>();

        this.PEDIDOS_PROVEEDORES_DETALLES = new HashSet<PEDIDOS_PROVEEDORES_DETALLES>();

    }


    public int ProductoID { get; set; }

    public string CodProducto { get; set; }

    public string Descripcion { get; set; }

    public int Stock { get; set; }

    public int StockReposicion { get; set; }

    public decimal PrecioCompra { get; set; }

    public decimal PrecioVenta { get; set; }

    public int CategoriaID { get; set; }

    public byte[] ImagenProducto { get; set; }

    public int ProveedorID { get; set; }

    public string Detalle { get; set; }

    public int TIvaID { get; set; }



    public virtual CATEGORIAS CATEGORIAS { get; set; }

    public virtual ICollection<PEDIDOS_CLIENTES_DETALLES> PEDIDOS_CLIENTES_DETALLES { get; set; }

    public virtual ICollection<PEDIDOS_PROVEEDORES_DETALLES> PEDIDOS_PROVEEDORES_DETALLES { get; set; }

    public virtual PROVEEDORES PROVEEDORES { get; set; }

    public virtual TIPO_IVA TIPO_IVA { get; set; }

}

}
