
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TIPO_IVA
{

    public TIPO_IVA()
    {

        this.PRODUCTOS = new HashSet<PRODUCTOS>();

    }


    public int TIvaID { get; set; }

    public decimal Porcentaje { get; set; }



    public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }

}

}
